version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: ecommerce-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - ecommerce-network

  # Redis
  redis:
    image: redis:7.0-alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - ecommerce-network

  # User Service
  user-service:
    build:
      context: .
      dockerfile: microservices/user-service/Dockerfile
    container_name: user-service
    env_file:
      - ./.env
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
      - redis
    networks:
      - ecommerce-network

  # Product Service
  product-service:
    build:
      context: .
      dockerfile: microservices/product-service/Dockerfile
    container_name: product-service
    env_file:
      - ./.env
    ports:
      - "3002:3000"
    depends_on:
      - mongodb
      - redis
      - user-service
    networks:
      - ecommerce-network

  # Order Service
  order-service:
    build:
      context: .
      dockerfile: microservices/order-service/Dockerfile
    container_name: order-service
    env_file:
      - ./.env
    ports:
      - "3003:3000"
    depends_on:
      - mongodb
      - redis
      - product-service
      - user-service
    networks:
      - ecommerce-network

  # Payment Service
  payment-service:
    build:
      context: .
      dockerfile: microservices/payment-service/Dockerfile
    container_name: payment-service
    env_file:
      - ./.env
    ports:
      - "3004:3000"
    depends_on:
      - mongodb
      - redis
      - order-service
    networks:
      - ecommerce-network

  # Nginx API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "80:80" # Port cho API Gateway
      - "443:443" # Cấu hình HTTPS sau này
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
    networks:
      - ecommerce-network

volumes:
  mongo_data:
  redis_data:


networks:
  ecommerce-network:
    driver: bridge
