# render.yaml - Phiên bản siêu đơn giản chỉ để tạo service

databases:
  - name: redis
    plan: free
    ipAllowList: [] # Trống có nghĩa là các service trong project được phép kết nối

services:
  # Service cho API Gateway
  - name: api-gateway
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./api-gateway/Dockerfile
    dockerContext: ./api-gateway
    healthCheckPath: /

  # Service cho User Microservice
  - name: user-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/user-service/Dockerfile
    dockerContext: .
    healthCheckPath: /api # Đường dẫn health check cho NestJS

  # Service cho Product Microservice
  - name: product-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/product-service/Dockerfile
    dockerContext: .
    healthCheckPath: /api

  # Service cho Order Microservice
  - name: order-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/order-service/Dockerfile
    dockerContext: .
    healthCheckPath: /api

  # Service cho Payment Microservice
  - name: payment-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/payment-service/Dockerfile
    dockerContext: .
    healthCheckPath: /api