# render.yaml - Chỉ khai báo service, không có biến môi trường

databases:
  - name: redis
    plan: free
    ipAllowList: [] # Trống có nghĩa là các service trong project được phép kết nối

services:
  # Service cho API Gateway
  - name: api-gateway
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./api-gateway/Dockerfile
    dockerContext: ./api-gateway
    healthCheckPath: /

  # Service cho User Microservice
  - name: user-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/user-service/Dockerfile
    dockerContext: .
    healthCheckPath: /health 
    envVars:
    - key: JWT_SECRET
      value: supersecretjwtkey
    - key: REDIS_HOST  
      value: cluster0.pis3u.mongodb.net
    - key: MONGO_USERNAME
      value: danghoa
    - key: MONGO_PASSWORD
      value: danghoa
    - key: MONGO_HOST
      value: cluster0.pis3u.mongodb.net
    - key: MONGO_DATABASE
      value: FinalE 

  # Service cho Product Microservice
  - name: product-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/product-service/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
    - key: JWT_SECRET
      value: supersecretjwtkey
    - key: MONGO_USERNAME
      value: danghoa
    - key: MONGO_PASSWORD
      value: danghoa
    - key: MONGO_HOST
      value: cluster0.pis3u.mongodb.net
    - key: MONGO_DATABASE
      value: FinalE 

  # Service cho Order Microservice
  - name: order-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/order-service/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
    - key: JWT_SECRET
      value: supersecretjwtkey
    - key: MONGO_USERNAME
      value: danghoa
    - key: MONGO_PASSWORD
      value: danghoa
    - key: MONGO_HOST
      value: cluster0.pis3u.mongodb.net
    - key: MONGO_DATABASE
      value: FinalE 

  # Service cho Payment Microservice
  - name: payment-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/payment-service/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
    - key: JWT_SECRET
      value: supersecretjwtkey
    - key: MONGO_USERNAME
      value: danghoa
    - key: MONGO_PASSWORD
      value: danghoa
    - key: MONGO_HOST
      value: cluster0.pis3u.mongodb.net
    - key: MONGO_DATABASE
      value: FinalE 