# render.yaml - Phiên bản cuối cùng đã được xác thực

# Định nghĩa các database
databases:
  - name: redis
    plan: free
    ipAllowList: [] # Cho phép các service trong project kết nối

# Định nghĩa các service ứng dụng
services:
  # Service cho API Gateway
  - name: api-gateway
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./api-gateway/Dockerfile
    dockerContext: ./api-gateway
    healthCheckPath: /

  # Service cho User Microservice
  - name: user-service
    type: pserv
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/user-service/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: ecommerce-secrets # CÚ PHÁP ĐÚNG
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString

  # Service cho Product Microservice
  - name: product-service
    type: pserv
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/product-service/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: ecommerce-secrets # CÚ PHÁP ĐÚNG

  # Service cho Order Microservice
  - name: order-service
    type: pserv
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/order-service/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: ecommerce-secrets # CÚ PHÁP ĐÚNG
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: PRODUCT_SERVICE_URL
        value: http://product-service:3000

  # Service cho Payment Microservice
  - name: payment-service
    type: pserv
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/payment-service/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: ecommerce-secrets # CÚ PHÁP ĐÚNG
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: ORDER_SERVICE_URL
        value: http://order-service:3000