# render.yaml - Phiên bản cuối cùng, an toàn và đúng chuẩn

databases:
  - name: redis
    plan: free
    ipAllowList: []

services:
  # Service cho API Gateway
  - name: api-gateway
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./api-gateway/Dockerfile
    dockerContext: ./api-gateway
    healthCheckPath: /
    # Gateway sẽ lấy các biến ..._SERVICE_URL từ group
    envGroup: ecommerce-secrets 

  # Service cho User Microservice
  - name: user-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/user-service/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    # Chỉ cần liên kết đến group
    envGroup: ecommerce-secrets

  # Service cho Product Microservice
  - name: product-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/product-service/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envGroup: ecommerce-secrets

  # Service cho Order Microservice
  - name: order-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/order-service/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envGroup: ecommerce-secrets

  # Service cho Payment Microservice
  - name: payment-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/payment-service/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envGroup: ecommerce-secrets