# Exported from Render on 2025-06-10T09:38:49Z
databases:
- name: redis
  databaseName: redis_g04h
  user: redis_g04h_user
  plan: free
  region: oregon
  ipAllowList: []
  postgresMajorVersion: "16"
services:
- type: web
  name: api-gateway
  runtime: docker
  repo: https://github.com/danghoa77/e_project
  plan: free
  envVars:
  - key: PAYMENT_SERVICE_URL
    sync: false
  - key: ORDER_SERVICE_URL
    sync: false
  - key: PRODUCT_SERVICE_URL
    sync: false
  - key: USER_SERVICE_URL
    sync: false
  - fromGroup: ecommerce-secrets
  region: oregon
  healthCheckPath: /
  dockerContext: ./api-gateway
  dockerfilePath: ./api-gateway/Dockerfile
  autoDeployTrigger: commit
- type: web
  name: payment-service
  runtime: docker
  repo: https://github.com/danghoa77/e_project
  plan: free
  envVars:
  - fromGroup: ecommerce-secrets
  region: oregon
  healthCheckPath: /api
  dockerContext: .
  dockerfilePath: ./microservices/payment-service/Dockerfile
  autoDeployTrigger: commit
- type: web
  name: order-service
  runtime: docker
  repo: https://github.com/danghoa77/e_project
  plan: free
  envVars:
  - fromGroup: ecommerce-secrets
  region: oregon
  healthCheckPath: /api
  dockerContext: .
  dockerfilePath: ./microservices/order-service/Dockerfile
  autoDeployTrigger: commit
- type: web
  name: product-service
  runtime: docker
  repo: https://github.com/danghoa77/e_project
  plan: free
  envVars:
  - fromGroup: ecommerce-secrets
  region: oregon
  healthCheckPath: /api
  dockerContext: .
  dockerfilePath: ./microservices/product-service/Dockerfile
  autoDeployTrigger: commit
- type: web
  name: user-service
  runtime: docker
  repo: https://github.com/danghoa77/e_project
  plan: free
  envVars:
  - fromGroup: ecommerce-secrets
  region: oregon
  healthCheckPath: /api
  dockerContext: .
  dockerfilePath: ./microservices/user-service/Dockerfile
  autoDeployTrigger: commit
version: "1"
