# render.yaml - Đã sửa lỗi service type cho gói miễn phí

databases:
  - name: redis
    plan: free
    ipAllowList: []

services:
  # Service cho API Gateway
  - name: api-gateway
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./api-gateway/Dockerfile
    dockerContext: ./api-gateway
    healthCheckPath: /

  # Service cho User Microservice
  - name: user-service
    type: web # SỬA LẠI: từ pserv thành web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/user-service/Dockerfile
    dockerContext: .
    healthCheckPath: /api # Thêm health check cho NestJS app
    envGroup: ecommerce-secrets
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString

  # Service cho Product Microservice
  - name: product-service
    type: web # SỬA LẠI: từ pserv thành web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/product-service/Dockerfile
    dockerContext: .
    healthCheckPath: /api
    envGroup: ecommerce-secrets

  # Service cho Order Microservice
  - name: order-service
    type: web # SỬA LẠI: từ pserv thành web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/order-service/Dockerfile
    dockerContext: .
    healthCheckPath: /api
    envGroup: ecommerce-secrets
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: PRODUCT_SERVICE_URL
        value: http://product-service:3000
      - key: USER_SERVICE_URL
        value: http://user-service:3000

  # Service cho Payment Microservice
  - name: payment-service
    type: web # SỬA LẠI: từ pserv thành web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/payment-service/Dockerfile
    dockerContext: .
    healthCheckPath: /api
    envGroup: ecommerce-secrets
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: ORDER_SERVICE_URL
        value: http://order-service:3000