# render.yaml - Phiên bản đơn giản hóa để tạo service

databases:
  - name: redis
    plan: free
    ipAllowList: []

services:
  # Service cho API Gateway
  - name: api-gateway
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./api-gateway/Dockerfile
    dockerContext: ./api-gateway
    healthCheckPath: /

  # Service cho User Microservice
  - name: user-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/user-service/Dockerfile
    dockerContext: .
    healthCheckPath: /api
    envGroup: ecommerce-secrets

  # Service cho Product Microservice
  - name: product-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/product-service/Dockerfile
    dockerContext: .
    healthCheckPath: /api
    envGroup: ecommerce-secrets

  # Service cho Order Microservice
  - name: order-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/order-service/Dockerfile
    dockerContext: .
    healthCheckPath: /api
    envGroup: ecommerce-secrets
    # Chúng ta vẫn cần các biến này để các service gọi nhau
    envVars:
      - key: PRODUCT_SERVICE_URL
        value: http://product-service:3000

  # Service cho Payment Microservice
  - name: payment-service
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./microservices/payment-service/Dockerfile
    dockerContext: .
    healthCheckPath: /api
    envGroup: ecommerce-secrets
    envVars:
      - key: ORDER_SERVICE_URL
        value: http://order-service:3000