# render.yaml - Phiên bản cuối cùng đã sửa lỗi

services:
  # Service cho Redis
  - name: redis
    type: redis
    plan: free

  # Service cho API Gateway
  - name: api-gateway
    type: web
    plan: free
    dockerfilePath: ./api-gateway/Dockerfile
    dockerContext: ./api-gateway
    healthCheckPath: /

  # Service cho User Microservice
  - name: user-service
    type: pserv
    plan: free
    dockerfilePath: ./microservices/user-service/Dockerfile
    dockerContext: .
    startCommand: node dist/microservices/user-service/main.js
    envVars:
      - fromGroup: ecommerce-secrets # <-- SỬA LẠI: Dùng fromGroup bên trong envVars

  # Service cho Product Microservice
  - name: product-service
    type: pserv
    plan: free
    dockerfilePath: ./microservices/product-service/Dockerfile
    dockerContext: .
    startCommand: node dist/microservices/product-service/main.js
    envVars:
      - fromGroup: ecommerce-secrets # <-- SỬA LẠI

  # Service cho Order Microservice
  - name: order-service
    type: pserv
    plan: free
    dockerfilePath: ./microservices/order-service/Dockerfile
    dockerContext: .
    startCommand: node dist/microservices/order-service/main.js
    envVars:
      - fromGroup: ecommerce-secrets # <-- SỬA LẠI
      - key: PRODUCT_SERVICE_URL
        value: http://product-service:3000
      - key: USER_SERVICE_URL
        value: http://user-service:3000

  # Service cho Payment Microservice
  - name: payment-service
    type: pserv
    plan: free
    dockerfilePath: ./microservices/payment-service/Dockerfile
    dockerContext: .
    startCommand: node dist/microservices/payment-service/main.js
    envVars:
      - fromGroup: ecommerce-secrets # <-- SỬA LẠI
      - key: ORDER_SERVICE_URL
        value: http://order-service:3000